@startuml

package "Entrypoints" {
    [Error Handlers] <-- [Routes]
    [Payloads] <- [Routes]
    [Routes] -> [Middlewares]
}

package "Errors" {
    [Exception]
}

package "Use Cases" {
    [Services] -> [Modules]
    [Schemas] <- [Services]

    [Routes] <--- [Services]
    [Exception] <- [Services]
    [Exception] <- [Modules]
    [Payloads] ... [Schemas]
}

package "External Entrypoints" {
    [Modules] <--- [Clients]
}

database "Database" {
    [Models] <- [Repositories]

    [Modules] <--- [Repositories]
    [Services] <--- [Repositories]
    [Exception] <-- [Repositories]
    [Schemas] ... [Models]
}

@enduml
