@startuml

package "Entrypoints" {

    package "HTTP" {
        [Error Handlers] <-- [Routes]
        [Payloads] <- [Routes]
        [Routes] -> [Middlewares]
   }

   package "Queue" {
        [Consumer]
   }

   package "GRPC" {
        [Server/Client]
   }

}

package "Errors" {
    [Exception]
}

package "Use Cases" {
    [Services] -> [Modules]
    [Schemas] <- [Services]

    [Routes] <--- [Services]
    [Consumer] <----- [Services]
    [Server/Client] <----- [Services]
    [Exception] <- [Services]
    [Exception] <- [Modules]
    [Payloads] ... [Schemas]
}

package "External Entrypoints" {
    [Modules] <--- [Clients]
}

database "Database" {
    [Models] <- [Repositories]

    [Modules] <--- [Repositories]
    [Services] <--- [Repositories]
    [Exception] <-- [Repositories]
    [Schemas] ... [Models]
}

@enduml
